export const EXERCISES = {
  BENCH_PRESS: 'Bench Press',
  OVERHEAD_PRESS: 'Overhead Press',
  INCLINE_BENCH: 'Incline Bench',
  CLOSE_GRIP_BENCH: 'Close Grip Bench',
  PULLUPS: 'Pull-ups',
  ABS: 'Abs'
} as const;

export const EXERCISE_TO_BASE_LIFT: Record<string, string> = {
  [EXERCISES.BENCH_PRESS]: EXERCISES.BENCH_PRESS,
  [EXERCISES.OVERHEAD_PRESS]: EXERCISES.OVERHEAD_PRESS,
  [EXERCISES.INCLINE_BENCH]: EXERCISES.BENCH_PRESS,
  [EXERCISES.CLOSE_GRIP_BENCH]: EXERCISES.BENCH_PRESS,
  [EXERCISES.PULLUPS]: EXERCISES.PULLUPS,
  [EXERCISES.ABS]: EXERCISES.ABS
};

export const DEFAULT_TRAINING_MAXES: Record<string, number> = {
  [EXERCISES.BENCH_PRESS]: 102.5,
  [EXERCISES.PULLUPS]: 20,
  [EXERCISES.ABS]: 25,
  [EXERCISES.OVERHEAD_PRESS]: 62.5
};
